server:
  port: 8305

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB      # ????????
      max-request-size: 51MB   # ????????
  application:
    name: blog-system
  datasource:
    url: jdbc:mysql://117.72.60.84:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

image:
  storage:
    root: /root/images
    public-base-url: ""

mybatis-plus:
  mapper-locations: classpath*:/Mapper/**/*.xml
  type-aliases-package: com.yu.blog.entity
